name: Build ms1 Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'microservice1/**'
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:
  buildPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        working-directory: microservice1
        run: |
            docker build -t $ECR_REGISTRY/elad/ms1:${{ github.sha }} .
            docker push $ECR_REGISTRY/elad/ms1:${{ github.sha }}

